<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><UseWPF>true</UseWPF></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FormatToolbox.Core\FormatToolbox.Core.csproj" />
    <PackageReference Include="PDFsharp-WPF" Version="6.2.4" />
    <PackageReference Include="PDFtoImage" Version="5.4.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <Content Include="tessdata\*.traineddata"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content>
    <Content Include="tessdata\pdf.ttf"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content>
  </ItemGroup>
</Project>
